# Generated by Django 5.1.3 on 2025-01-30 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Customer",
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={
                "verbose_name": "CastomUser",
                "verbose_name_plural": "CastomUsers",
            },
        ),
        migrations.AlterModelTable(
            name="customer",
            table="users_castomuser",
        ),
    ]
