# Generated by Django 4.2.2 on 2025-01-31 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("users", "0002_rename_user_customer_alter_customer_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Customer",
            new_name="User",
        ),
    ]
